name: setup
inputs:
  node-version:
    description: Node version override
runs:
  using: composite
  steps:
    - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ (inputs.node-version == '' && '.node-version') || null }}
    - run: npm ci --ignore-scripts
      shell: bash
