name: setup
inputs:
  node-version:
    description: Node version override
runs:
  using: composite
  steps:
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ (inputs.node-version == '' && '.node-version') || null }}
        cache: npm
    - run: npm ci --ignore-scripts
      shell: bash
