name: setup
inputs:
  node-version:
    description: Node version override
runs:
  using: composite
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ (inputs.node-version == '' && '.node-version') || null }}
    - run: npm ci --ignore-scripts
      shell: bash
