name: build
on: push

permissions:
  contents: read

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        node: [16, '', 20, 22, 23]
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}
      - run: npm run build
        env:
          JOBS: 3
          ZSTD_NAPI_ENABLE_GCOV: ${{ (matrix.node == '' && 1) || null }}
      - run: npm run ${{ (matrix.node == '' && 'test-coverage') || 'test' }}
      - name: Submit coverage data to Codecov
        if: matrix.node == ''
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3 # v5.3.1
        with:
          use_oidc: true

  uasan-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}
      - run: npx -c 'node-gyp rebuild --napi_build_version=8 --zstd_asan=1 --zstd_ubsan=1'
        env:
          CC: clang
          CXX: clang++
          JOBS: 3
      - run: clang --version
      - run: npm run test
        env:
          # Preloading ASAN into Node generates a ton of false-positive leaks
          ASAN_OPTIONS: detect_leaks=0
          LD_PRELOAD: /usr/lib/clang/15/lib/linux/libclang_rt.asan-x86_64.so

  npm-package:
    uses: ./.github/workflows/npm_package.yml
    permissions:
      actions: read
      contents: write
      id-token: write

  prebuilds:
    uses: ./.github/workflows/prebuilds.yml
    permissions:
      actions: read
      contents: write
      id-token: write

  other-ts-versions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
      - run: |
          for version in 4.5 4.6 4.7 4.8 4.9 5.0 5.1 5.2 5.3 5.4 5.5 5.6 5.7; do
            echo "=== Typescript ${version} ==="
            npx -y --package=typescript@$version -- tsc -p tsconfig.old-ts.json
          done

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
      - run: ./node_modules/.bin/tsc -p .
      - run: npm run lint
      - name: Check JS/TS is formatted with Prettier
        run: ./node_modules/.bin/prettier --check .
      - name: Check C++ is formatted with clang-format
        run: |
          clang-format-18 -i src/*
          git diff --stat --exit-code src/
