name: build
on: push

permissions:
  contents: read

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        node: [18, '', 22, 24]
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}
      - run: npm run build
        env:
          JOBS: 3
          ZSTD_NAPI_ENABLE_GCOV: ${{ (matrix.node == '' && 1) || null }}
      - run: npm run ${{ (matrix.node == '' && 'test-coverage') || 'test' }}
      - name: Submit coverage data to Codecov
        if: matrix.node == ''
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          use_oidc: true

  npm-package:
    uses: ./.github/workflows/npm_package.yml
    permissions:
      actions: read
      contents: write
      id-token: write

  prebuilds:
    uses: ./.github/workflows/prebuilds.yml
    permissions:
      actions: read
      contents: write
      id-token: write

  other-ts-versions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
      - run: |
          for version in 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9; do
            echo "=== Typescript ${version} ==="
            npx -y --package=typescript@$version -- tsc -p .
          done
          echo "=== Typescript 7.x preview ==="
          npx -y --package=@typescript/native-preview@latest -- tsc -p .

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
      - run: ./node_modules/.bin/tsc -p .
      - run: npm run lint
      - name: Check JS/TS is formatted with Prettier
        run: ./node_modules/.bin/prettier --check .
      - name: Check C++ is formatted with clang-format
        run: |
          clang-format-18 -i src/*
          git diff --stat --exit-code src/
