name: build
on: push

permissions:
  contents: read

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        node: [18, '', 22, 24]
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}
      - run: npm run build
        env:
          JOBS: 3
          ZSTD_NAPI_ENABLE_GCOV: ${{ (matrix.node == '' && 1) || null }}
      - run: npm run ${{ (matrix.node == '' && 'test-coverage') || 'test' }}
      - name: Submit coverage data to Codecov
        if: matrix.node == ''
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          use_oidc: true

  npm-package:
    uses: ./.github/workflows/npm_package.yml
    permissions:
      actions: read
      contents: write
      id-token: write

  prebuilds:
    uses: ./.github/workflows/prebuilds.yml
    permissions:
      actions: read
      contents: write
      id-token: write

  other-ts-versions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
      - run: |
          for version in 5.2 5.3 5.4 5.5 5.6 5.7 5.8; do
            echo "=== Typescript ${version} ==="
            npx -y --package=typescript@$version -- tsc -p .
          done

  platform-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2019
          - windows-2022
          - windows-2025
        node: [12.22.0, 14.17.0, 16, 18, 20, 22, 23, 24]
        exclude:
          # These pre-date arm64 Darwin
          - { os: macos-14, node: 12.22.0 }
          - { os: macos-14, node: 14.17.0 }
          - { os: macos-15, node: 12.22.0 }
          - { os: macos-15, node: 14.17.0 }
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          submodules: recursive
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm i -g npm@8
        # Install npm 8 first on Windows with Node 14, since the npm 6.x version
        # it ships with seems to be unable to directly install npm 9.x (throws a
        # bogus permission error) only on Windows.
        if: matrix.node == '12.22.0' || (matrix.node == '14.17.0' && runner.os == 'Windows')
      - run: npm i -g npm@9
        if: matrix.node == '14.17.0'
      - run: sudo apt-get -y install python3-setuptools
        if: (matrix.node == '12.22.0' || matrix.node == '14.17.0' || matrix.node == '16') && runner.os == 'Linux'
      - run: pip3 install --break-system-packages setuptools
        if: (matrix.node == '12.22.0' || matrix.node == '14.17.0' || matrix.node == '16') && runner.os == 'macOS'
      - run: npm ci --prod --ignore-scripts
      - run: npm run build
        env:
          JOBS: 3
      - run: npm ci --ignore-scripts
      - name: Check for unexpected global dynamic symbols
        run: |
          # TODO: Use -U and -W once ubuntu-22.04 is dead
          if nm -gD --defined-only build/Release/binding.node |
              grep -E -v 'T _?(napi_register_module|node_api_module_get_api_version)|[VW] '; then
            echo "Unexpected global dynamic symbol definitions found in binary"
            exit 1
          fi
          if nm -gD build/Release/binding.node | grep ZSTD; then
            echo "Unexpected global ZSTD symbols found in binary"
            exit 1
          fi
        if: runner.os != 'Windows'
      - run: npm run test
        if: matrix.node != '12.22.0' # Recent Jest can't run on 12.x

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup
      - run: ./node_modules/.bin/tsc -p .
      - run: npm run lint
      - name: Check JS/TS is formatted with Prettier
        run: ./node_modules/.bin/prettier --check .
      - name: Check C++ is formatted with clang-format
        run: |
          clang-format-18 -i src/*
          git diff --stat --exit-code src/
