name: npm-package
on:
  workflow_call:
    inputs:
      provenance:
        type: boolean
      upload-assets:
        type: boolean

permissions:
  contents: read

jobs:
  build-unsigned:
    runs-on: ubuntu-22.04
    if: '!inputs.provenance'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - run: ./node_modules/.bin/tsc -p tsconfig.emit.json
      - id: npm_pack
        name: Build npm package
        run: echo "package=$(npm pack -s)" >> "$GITHUB_OUTPUT"
      - name: Upload NPM package
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: npm-package
          path: ${{ steps.npm_pack.outputs.package }}

  build-provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v2.0.0
    if: inputs.provenance
    permissions:
      actions: read
      contents: read
      id-token: write
    with:
      node-version-file: .node-version
      run-scripts: submodule-update,ci-ignore-scripts

  upload:
    if: inputs.upload-assets && !(failure() || cancelled())
    needs: [build-provenance, build-unsigned]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - if: inputs.provenance
        uses: slsa-framework/slsa-github-generator/actions/nodejs/secure-package-download@5a775b367a56d5bd118a224a811bba288150a563 # v2.0.0
        with:
          name: ${{ needs.build-provenance.outputs.package-download-name }}
          path: ${{ needs.build-provenance.outputs.package-name }}
          sha256: ${{ needs.build-provenance.outputs.package-download-sha256 }}

      - if: '!inputs.provenance'
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: npm-package

      - run: gh release upload '${{ github.ref_name }}' zstd-napi-*.tgz
        env:
          GH_TOKEN: ${{ github.token }}

      - if: inputs.provenance
        uses: slsa-framework/slsa-github-generator/actions/nodejs/secure-attestations-download@5a775b367a56d5bd118a224a811bba288150a563 # v2.0.0
        with:
          name: ${{ needs.build-provenance.outputs.provenance-download-name }}
          path: attestations
          sha256: ${{ needs.build-provenance.outputs.provenance-download-sha256 }}

      - if: inputs.provenance
        run: gh release upload '${{ github.ref_name }}' 'attestations/${{ needs.build-provenance.outputs.provenance-download-name }}/${{ needs.build-provenance.outputs.provenance-name }}'
        env:
          GH_TOKEN: ${{ github.token }}
