name: npm-package
on: [workflow_call]

permissions:
  contents: read

jobs:
  build-unsigned:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - run: ./node_modules/.bin/tsc -p tsconfig.emit.json
      - id: npm_pack
        name: Build npm package
        run: echo "package=$(npm pack)" >> "$GITHUB_OUTPUT"
      - name: Upload NPM package
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
        with:
          name: package
          path: ${{ steps.npm_pack.outputs.package }}
