name: npm-package
on:
  workflow_call:
    inputs:
      provenance:
        type: boolean
      upload-assets:
        type: boolean
    outputs:
      package-name:
        value: ${{ jobs.build-provenance.outputs.package-name }}
      package-download-name:
        value: ${{ jobs.build-provenance.outputs.package-download-name }}
      package-download-sha256:
        value: ${{ jobs.build-provenance.outputs.package-download-sha256 }}
      provenance-name:
        value: ${{ jobs.build-provenance.outputs.provenance-name }}
      provenance-download-name:
        value: ${{ jobs.build-provenance.outputs.provenance-download-name }}
      provenance-download-sha256:
        value: ${{ jobs.build-provenance.outputs.provenance-download-sha256 }}

permissions:
  contents: read

jobs:
  build-unsigned:
    runs-on: ubuntu-24.04
    if: '!inputs.provenance'
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - run: ./node_modules/.bin/tsc -p tsconfig.emit.json
      - id: npm_pack
        name: Build npm package
        run: echo "package=$(npm pack -s)" >> "$GITHUB_OUTPUT"
      - id: upload
        name: Upload NPM package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: npm-package
          path: ${{ steps.npm_pack.outputs.package }}

  build-provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v2.1.0
    if: inputs.provenance
    permissions:
      actions: read
      contents: read
      id-token: write
    with:
      node-version-file: .node-version
      run-scripts: submodule-update,ci-ignore-scripts

  test-package:
    if: '!(failure() || cancelled())'
    needs: [build-provenance, build-unsigned]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04, windows-2025]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          path: repo
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: repo/.node-version
      - if: inputs.provenance
        uses: slsa-framework/slsa-github-generator/actions/nodejs/secure-package-download@f7dd8c54c2067bafc12ca7a55595d5ee9b75204a # v2.1.0
        with:
          name: ${{ needs.build-provenance.outputs.package-download-name }}
          path: ${{ needs.build-provenance.outputs.package-name }}
          sha256: ${{ needs.build-provenance.outputs.package-download-sha256 }}
      - if: '!inputs.provenance'
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          artifact-ids: ${{ needs.build-unsigned.outputs.artifact-id }}
      - run: npm i --build-from-source ./zstd-napi-*.tgz
        shell: bash
      - run: node -p 'require("zstd-napi/binding").versionString()'
      - if: matrix.os == 'ubuntu-24.04'
        run: |
          # Latest for Node 16 that work with TS 4.5
          npm i --save-dev @types/node@16.18.65 @tsconfig/node16@1.0.3
          cat > index.ts <<EOF
          import * as zstd from "zstd-napi";
          import * as binding from "zstd-napi/binding";
          console.log(binding.versionString());
          console.log(zstd.compress(Buffer.from('hello')));
          EOF
          cat > tsconfig.json <<EOF
          {
            "extends": "@tsconfig/node16",
            "compilerOptions": {
              "esModuleInterop": false,
              "skipLibCheck": false
            },
            "include": ["index.ts"]
          }
          EOF
          for version in 4.5 4.6 4.7 4.8 4.9 5.0 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8; do
            echo "=== Typescript ${version} ==="
            npx -y --package=typescript@$version -- tsc -p .
            node index.js
          done
          # TS 5.9+ requires newer @types/node version
          npm i --save-dev @types/node@16.18.126
          for version in 5.9; do
            echo "=== Typescript ${version} ==="
            npx -y --package=typescript@$version -- tsc -p .
            node index.js
          done
          echo "=== Typescript 7.x preview ==="
          npx -y --package=@typescript/native-preview@latest -- tsc -p .
          node index.js

  upload:
    if: inputs.upload-assets && !(failure() || cancelled())
    needs: [build-provenance, build-unsigned, test-package]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - if: inputs.provenance
        uses: slsa-framework/slsa-github-generator/actions/nodejs/secure-package-download@f7dd8c54c2067bafc12ca7a55595d5ee9b75204a # v2.1.0
        with:
          name: ${{ needs.build-provenance.outputs.package-download-name }}
          path: ${{ needs.build-provenance.outputs.package-name }}
          sha256: ${{ needs.build-provenance.outputs.package-download-sha256 }}

      - if: '!inputs.provenance'
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          artifact-ids: ${{ needs.build-unsigned.outputs.artifact-id }}

      - run: gh release upload '${{ github.ref_name }}' zstd-napi-*.tgz
        env:
          GH_TOKEN: ${{ github.token }}

      - if: inputs.provenance
        uses: slsa-framework/slsa-github-generator/actions/nodejs/secure-attestations-download@f7dd8c54c2067bafc12ca7a55595d5ee9b75204a # v2.1.0
        with:
          name: ${{ needs.build-provenance.outputs.provenance-download-name }}
          path: attestations
          sha256: ${{ needs.build-provenance.outputs.provenance-download-sha256 }}

      - if: inputs.provenance
        run: gh release upload '${{ github.ref_name }}' 'attestations/${{ needs.build-provenance.outputs.provenance-download-name }}/${{ needs.build-provenance.outputs.provenance-name }}'
        env:
          GH_TOKEN: ${{ github.token }}
