name: release
on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: read

jobs:
  sanity-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Verify package.json has correct version for tag
        run: |
          pkg_json="$(jq -r .version package.json)"
          tag="${{ github.ref_name }}"
          tag_ver="$(sed -E 's/^v([^-]+)(-.*)?$/\1/' <<< "$tag")"
          if [[ "$pkg_json" != "$tag_ver" ]]; then
            echo "::error::package.json has version ${pkg_json}, expected ${tag_ver}"
            exit 1
          fi

  create-draft-release:
    needs: [sanity-check]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: gh release create ${{ github.ref_name }} -d --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ github.token }}

  npm-package:
    needs: [create-draft-release]
    uses: ./.github/workflows/npm_package.yml
    permissions:
      actions: read
      contents: write
      id-token: write
    with:
      provenance: true
      upload-assets: true

  prebuilds:
    needs: [create-draft-release]
    uses: ./.github/workflows/prebuilds.yml
    permissions:
      actions: read
      contents: write
      id-token: write
    with:
      provenance: true
      upload-assets: true

  npm-publish:
    if: "!contains(github.ref_name, '-')"
    environment: npm-publish
    needs: [npm-package, prebuilds]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org
      - uses: slsa-framework/slsa-github-generator/actions/nodejs/secure-package-download@5a775b367a56d5bd118a224a811bba288150a563 # v2.0.0
        with:
          name: ${{ needs.npm-package.outputs.package-download-name }}
          path: ${{ needs.npm-package.outputs.package-name }}
          sha256: ${{ needs.npm-package.outputs.package-download-sha256 }}
      - uses: slsa-framework/slsa-github-generator/actions/nodejs/secure-attestations-download@5a775b367a56d5bd118a224a811bba288150a563 # v2.0.0
        with:
          name: ${{ needs.npm-package.outputs.provenance-download-name }}
          path: attestations
          sha256: ${{ needs.npm-package.outputs.provenance-download-sha256 }}
      - run: npm publish '${{ needs.npm-package.outputs.package-name }}' --provenance-file='attestations/${{ needs.npm-package.outputs.provenance-download-name }}/${{ needs.npm-package.outputs.provenance-name }}'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
